### ISSUE TITLE
Add new geometry class for triangulated meshes

### ISSUE THREAD

**Issue by pbarbarant** [ott-jax/ott#528]
**Is your feature request related to a problem? Please describe.**
Point clouds maintain the notion of absolute coordinates but do not allow for the computation of geodesics, on the other hand graphs take adjacency matrices as inputs, regardless of the original basis/orientation in 3D space.

**Describe the solution you'd like**
An implementation of the form `mesh.Mesh(coordinates, faces)` which generates a geometry object with the default cost defined as the geodesic distance (heat kernel for example) over the mesh.

**Describe alternatives you've considered**
As for now the best way is to instantiate a point cloud and pipe in a custom cost matrix computed with a package like `tvb-gdist`.

**Additional context**
This is specific to dimension 3 yet could benefit to a lot of OT applications (shape alignment, computational anatomy, etc...)

**Comment by michalk8** [comment]
We already have 2 graph-based geometries, namely [Geodesic](https://ott-jax.readthedocs.io/en/latest/_autosummary/ott.geometry.geodesic.Geodesic.html#ott.geometry.geodesic.Geodesic) and [Graph](https://ott-jax.readthedocs.io/en/latest/_autosummary/ott.geometry.graph.Graph.html#ott.geometry.graph.Graph); would close this for now since from what I think you're suggesting is just to create a graph from a 2D/3D mesh, which should be fairly easy.
